[package]
name = "top_sixteen"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../types" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.132"
reqwest = { version = "0.12.9", features = ["json"] }
anyhow = "1.0.93"
