name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux
            target: x86_64-unknown-linux-musl

          - build: macos
            target: x86_64-apple-darwin

          - build: windows-gnu
            target: x86_64-pc-windows-gnu
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      #      - name: Install Rust
      #        uses: dtolnay/rust-toolchain@stable
      #        with:
      #          targets: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --target ${{ matrix.target }}