name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release