name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux
            os: ubuntu-latest
          - build: windows
            os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build release binary
        run: cargo build --release
      - name: Prepare release package
        run: |
          mkdir dist
          cp target/release/cedh-stats dist/
          cp README.md dist/ || true # Include README if available
          
          # Windows: Create ZIP
          if [ "$RUNNER_OS" == "Windows" ]; then
            powershell Compress-Archive -Path dist/* -DestinationPath cedh-stats-${{ matrix.build }}.zip
          else
            # Linux/macOS: Create tar.gz
            tar -czvf cedh-stats-${{ matrix.build }}.tar.gz -C dist .
          fi
      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cedh-stats-${{ matrix.build }}
          path: |
            cedh-stats-${{ matrix.build }}.zip
            cedh-stats-${{ matrix.build }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Linux archive
        uses: actions/download-artifact@v3
        with:
          name: cedh-stats-linux
          path: linux

      - name: Download Windows archive
        uses: actions/download-artifact@v3
        with:
          name: cedh-stats-windows
          path: windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux/cedh-stats-linux.tar.gz
            windows/cedh-stats-windows.zip
          token: ${{ secrets.GITHUB_TOKEN }}