name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build release binary
        run: cargo build --release
      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cedh-stats-linux
          path: target/release/cedh-stats

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: my_project-linux
          path: my_project

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: cedh-stats/cedh-stats-linux
          token: ${{ secrets.GITHUB_TOKEN }}